import { Link } from 'react-router-dom'
import { useAuth } from '../auth'

const SECTIONS: [string, string[]][] = [
  ['A practice tool, not a hiring assessment', [
    'ProManAI helps you practise product manager interviews. It is not a recruiter, an employer or a certification body.',
    'Scores and feedback are estimates generated automatically from what you said. They are not a prediction of how any company would assess you, and they are not a guarantee of any interview result or job offer.',
  ]],
  ['The AI can be wrong', [
    'Questions, follow-ups and feedback are generated by AI and can be inaccurate, incomplete or inconsistent. Use your own judgement and treat feedback as one input, not a verdict.',
    'In this prototype, scores come from simple rules (answer length and keywords), not from a trained evaluator.',
    'Speech-to-text can mishear you. Check and edit your answer before you submit it: the text you submit is what gets scored.',
  ]],
  ['Voice input and browser support', [
    'Voice answers work in desktop Chrome or Edge. Other browsers and most phones cannot turn speech into text here, so you would type your answers instead.',
    'To turn speech into text, Chrome and Edge may send your audio to their own speech services (Google or Microsoft), under those companies\' terms. ProManAI does not store audio: only the text of your answers is saved.',
  ]],
  ['Fictional scenarios and no affiliation', [
    'Companies, products, people and numbers in interview questions and sample interview data are fictional. Any resemblance to real companies is coincidental. The exception is the AI tools catalogue, which lists real products.',
    'ProManAI is not affiliated with or endorsed by any company or tool named on the site. Product names belong to their owners.',
  ]],
  ['What you should not share', [
    'Do not share confidential information from a current or past employer, or interview questions you agreed to keep private.',
    'Do not include personal details about other people in your answers or in anything you publish.',
  ]],
  ['Community content', [
    'Interview experiences, rankings, votes and tool reviews come from other users and reflect their own views. Reviewers are not verified unless marked as verified.',
    'Facts about AI tools (makers, free plans, platforms) were checked against the sources shown on each tool, on the date shown. Prices and plans change often, so confirm on the official site. Tool reviews marked Sample were written for this demo and are not from real users.',
  ]],
  ['This prototype', [
    'This is a prototype with sample data. No emails are sent, no payments are taken, and all data is reset when the demo server restarts.',
  ]],
]

export default function Disclaimer() {
  const { user } = useAuth()
  return (
    <div className="doc">
      <Link to={user ? '/dashboard' : '/'} className="brand" style={{ color: 'var(--ink)', padding: 0 }}><i />ProManAI</Link>
      <h1>Disclaimer</h1>
      <p className="muted">Please read this before you rely on anything ProManAI tells you.</p>
      {SECTIONS.map(([title, paras]) => (
        <section key={title} className="stack" style={{ gap: 8 }}>
          <h2>{title}</h2>
          {paras.map((p) => <p key={p}>{p}</p>)}
        </section>
      ))}
      <p><Link to={user ? '/dashboard' : '/'}>{user ? 'Back to the dashboard' : 'Back to the home page'}</Link></p>
    </div>
  )
}
